# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 1.0
notifications:
  email: false
after_success:
    # push coverage results to Codecov
    - julia -e 'cd(Pkg.dir("Espresso")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'